#!/usr/bin/env bash
#Define local host entry and facebook entry
echo "Updating the /etc/hosts file..."
{
    echo "127.0.0.2   localhost"
    echo "8.8.8.8     facebook.com"
} | sudo tee /etc/hosts > /dev/null